[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://app.storyblok.com;"
    X-Frame-Options = "ALLOW-FROM https://app.storyblok.com"
    Access-Control-Allow-Origin = "app.storyblok.com"
    Access-Control-Allow-Credentials = "true"

[build]
  command = "astro build"
  functions = "/.netlify/functions"
  publish = "dist"
    
[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect